"""ScopeBuddy observations and stub generator."""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class ScopeBuddyObservation:
    games_with_scb_launch: set[str] = field(default_factory=set)
    missing_configs: list[str] = field(default_factory=list)
    orphan_configs: list[str] = field(default_factory=list)


def observe(
    configs_dir: Path,
    installed_appids: list[str],
    launch_options: dict[str, str | None],
) -> ScopeBuddyObservation:
    """Compare existing configs against installed games + launch options.

    - games_with_scb_launch: appids whose launch options contain 'scopebuddy'
    - missing_configs: appid uses scopebuddy but <appid>.conf is missing
    - orphan_configs: <appid>.conf exists but appid is not installed
    """
    installed = set(installed_appids)
    existing = set()
    if configs_dir.is_dir():
        for p in configs_dir.glob("*.conf"):
            existing.add(p.stem)

    with_scb = {
        appid for appid, opts in launch_options.items()
        if opts and "scopebuddy" in opts
    }

    missing = sorted(with_scb - existing)
    orphans = sorted(existing - installed)

    return ScopeBuddyObservation(
        games_with_scb_launch=with_scb,
        missing_configs=missing,
        orphan_configs=orphans,
    )


_STUB_TEMPLATE = """\
# {name}
# (auto-generated by steam-manager)

"""


def init_stub(target: Path, name: str, force: bool = False) -> None:
    """Write an L1 stub (header + auto-gen comment + blank line).
    Raises FileExistsError if target exists and force=False."""
    if target.exists() and not force:
        raise FileExistsError(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_STUB_TEMPLATE.format(name=name))


def delete_config(path: Path) -> None:
    """Remove one per-game config file. Propagates FileNotFoundError when the
    file is already gone — callers decide whether that is an error."""
    path.unlink()
